/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantalla;

/**
 *
 * @author Santiago
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        sesion = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pwLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        iniciarPanel = new javax.swing.JPanel();
        iniciarLabel = new javax.swing.JLabel();
        registrarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pwTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\logo.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 290, 150));

        logoname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 255, 255));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("MAS POCO ALQUILO");
        jPanel1.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 290, 30));

        city.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\city.png")); // NOI18N
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        favicon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        favicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\favicon.png")); // NOI18N
        favicon.setText("MAS POCO ALQUILO");
        jPanel1.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 230, 30));

        sesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sesion.setText("INICIAR SESION");
        jPanel1.add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userLabel.setText("USUARIO");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        userTxt.setForeground(new java.awt.Color(51, 51, 51));
        userTxt.setToolTipText("");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 370, 30));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 370, 10));

        pwLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pwLabel.setText("CONTRASENA");
        jPanel1.add(pwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 10));

        iniciarPanel.setBackground(new java.awt.Color(0, 134, 190));

        iniciarLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iniciarLabel.setForeground(new java.awt.Color(255, 255, 255));
        iniciarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarLabel.setText("INICIAR SESION");
        iniciarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iniciarPanelLayout = new javax.swing.GroupLayout(iniciarPanel);
        iniciarPanel.setLayout(iniciarPanelLayout);
        iniciarPanelLayout.setHorizontalGroup(
            iniciarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        iniciarPanelLayout.setVerticalGroup(
            iniciarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(iniciarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 370, 30));

        registrarPanel.setBackground(new java.awt.Color(0, 134, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATE AQUI");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registrarPanelLayout = new javax.swing.GroupLayout(registrarPanel);
        registrarPanel.setLayout(registrarPanelLayout);
        registrarPanelLayout.setHorizontalGroup(
            registrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        registrarPanelLayout.setVerticalGroup(
            registrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(registrarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 370, 30));

        pwTxt.setBorder(null);
        jPanel1.add(pwTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 370, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed

    }//GEN-LAST:event_userTxtMousePressed

    private void iniciarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarLabelMouseClicked
        negocios.sqlUsuarios.inicioSesion();
    }//GEN-LAST:event_iniciarLabelMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        registro pantallaRegistro = new registro();
        pantallaRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel favicon;
    public static javax.swing.JLabel iniciarLabel;
    public static javax.swing.JPanel iniciarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoname;
    private javax.swing.JLabel pwLabel;
    public static javax.swing.JTextField pwTxt;
    private javax.swing.JPanel registrarPanel;
    private javax.swing.JLabel sesion;
    private javax.swing.JLabel userLabel;
    public static javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
