/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantalla;

import negocios.sqlUsuarios;
import negocios.usuarios;
import pantalla.registro;
import pantalla.inicio;

/**
 *
 * @author Santiago
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoname = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        userRegTxt = new javax.swing.JTextField();
        userRegLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        surnameLabel = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        emailLabel = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        emailLabel1 = new javax.swing.JLabel();
        emailTxt1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pwRegLabel = new javax.swing.JLabel();
        pwRegTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        comoTipo = new javax.swing.JComboBox<>();
        ejecutarRegistroPanel = new javax.swing.JPanel();
        ejecutarRegistroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 255, 255));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("MAS POCO ALQUILO");
        jPanel1.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 290, 30));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\logo.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 290, 150));

        city.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\city.png")); // NOI18N
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        favicon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        favicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\favicon.png")); // NOI18N
        favicon.setText("MAS POCO ALQUILO - REGISTRO");
        jPanel1.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 340, 30));

        userRegTxt.setForeground(new java.awt.Color(51, 51, 51));
        userRegTxt.setToolTipText("");
        userRegTxt.setBorder(null);
        userRegTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userRegTxtMousePressed(evt);
            }
        });
        userRegTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userRegTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 370, 30));

        userRegLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userRegLabel.setText("USUARIO");
        jPanel1.add(userRegLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 10));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setText("NOMBRE");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        nameTxt.setForeground(new java.awt.Color(51, 51, 51));
        nameTxt.setToolTipText("");
        nameTxt.setBorder(null);
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameTxtMousePressed(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 370, 30));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 370, 20));

        surnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        surnameLabel.setText("APELLIDO");
        jPanel1.add(surnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        surnameTxt.setForeground(new java.awt.Color(51, 51, 51));
        surnameTxt.setToolTipText("");
        surnameTxt.setBorder(null);
        surnameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                surnameTxtMousePressed(evt);
            }
        });
        surnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(surnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 370, 30));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, 20));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("EMAIL");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        emailTxt.setForeground(new java.awt.Color(51, 51, 51));
        emailTxt.setToolTipText("");
        emailTxt.setBorder(null);
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 20));

        emailLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel1.setText("EMAIL");
        jPanel1.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        emailTxt1.setForeground(new java.awt.Color(204, 204, 204));
        emailTxt1.setText("Ingrese su nombre de usuario");
        emailTxt1.setToolTipText("");
        emailTxt1.setBorder(null);
        emailTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxt1MousePressed(evt);
            }
        });
        emailTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 30));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 20));

        pwRegLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pwRegLabel.setText("CONTRASENA");
        jPanel1.add(pwRegLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        pwRegTxt.setForeground(new java.awt.Color(51, 51, 51));
        pwRegTxt.setToolTipText("");
        pwRegTxt.setBorder(null);
        pwRegTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwRegTxtMousePressed(evt);
            }
        });
        pwRegTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwRegTxtActionPerformed(evt);
            }
        });
        jPanel1.add(pwRegTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, 30));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 370, 10));

        comoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Agente Inmobiliario", "Cliente" }));
        comoTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        comoTipo.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        comoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoTipoActionPerformed(evt);
            }
        });
        jPanel1.add(comoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 220, 60));

        ejecutarRegistroPanel.setBackground(new java.awt.Color(0, 134, 190));

        ejecutarRegistroLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejecutarRegistroLabel.setForeground(new java.awt.Color(255, 255, 255));
        ejecutarRegistroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ejecutarRegistroLabel.setText("REGISTRAR");
        ejecutarRegistroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ejecutarRegistroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejecutarRegistroLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ejecutarRegistroPanelLayout = new javax.swing.GroupLayout(ejecutarRegistroPanel);
        ejecutarRegistroPanel.setLayout(ejecutarRegistroPanelLayout);
        ejecutarRegistroPanelLayout.setHorizontalGroup(
            ejecutarRegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ejecutarRegistroPanelLayout.createSequentialGroup()
                .addComponent(ejecutarRegistroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ejecutarRegistroPanelLayout.setVerticalGroup(
            ejecutarRegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecutarRegistroPanelLayout.createSequentialGroup()
                .addComponent(ejecutarRegistroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(ejecutarRegistroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userRegTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegTxtMousePressed

    }//GEN-LAST:event_userRegTxtMousePressed

    private void userRegTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegTxtActionPerformed

    private void nameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtMousePressed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void surnameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnameTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTxtMousePressed

    private void surnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTxtActionPerformed

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtMousePressed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void emailTxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxt1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt1MousePressed

    private void emailTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt1ActionPerformed

    private void pwRegTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwRegTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwRegTxtMousePressed

    private void pwRegTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwRegTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwRegTxtActionPerformed

    private void ejecutarRegistroLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarRegistroLabelMouseClicked
        negocios.sqlUsuarios.leerDatosPersonaAgregar();
    }//GEN-LAST:event_ejecutarRegistroLabelMouseClicked

    private void comoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comoTipoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    public static javax.swing.JComboBox<String> comoTipo;
    private javax.swing.JLabel ejecutarRegistroLabel;
    private javax.swing.JPanel ejecutarRegistroPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    public static javax.swing.JTextField emailTxt;
    private javax.swing.JTextField emailTxt1;
    private javax.swing.JLabel favicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoname;
    private javax.swing.JLabel nameLabel;
    public static javax.swing.JTextField nameTxt;
    private javax.swing.JLabel pwRegLabel;
    public static javax.swing.JTextField pwRegTxt;
    private javax.swing.JLabel surnameLabel;
    public static javax.swing.JTextField surnameTxt;
    private javax.swing.JLabel userRegLabel;
    public static javax.swing.JTextField userRegTxt;
    // End of variables declaration//GEN-END:variables
}
